import { NextResponse } from "next/server";
import { db } from "@/lib/db";
import { engagements } from "@/models/schema";
import { getSession } from "@/lib/session";
import { getActiveWorkspace } from "@/lib/workspace";
import { and, eq } from "drizzle-orm";
import { buildScriptPack } from "@/features/pin-down/server/script-builder";

/**
 * Manual "Regenerate now" for Pin-Down's hero + breakout video scripts and
 * recording checklist — content generated once during onboarding
 * (see onboarding-service.ts) from offer/voice/questions/proof/casting
 * fields, none of which re-run automatically when those fields are edited
 * later in the client details drawer.
 *
 * Pure content generation only — writes pinDownScriptPack and nothing
 * else. Does NOT touch the confirmation page or attempt any deploy; see
 * client-details-drawer.tsx for why a live-page regenerate isn't offered
 * here (approval-gated hosting deploy, out of scope for a one-click
 * action).
 */
export async function POST(
  _req: Request,
  { params }: { params: Promise<{ id: string }> }
) {
  try {
    const { id } = await params;
    const session = await getSession();
    if (!session?.whopUserId) {
      return NextResponse.json({ error: "Unauthorized" }, { status: 401 });
    }
    const activeWorkspace = await getActiveWorkspace(session.whopUserId);

    const [row] = await db
      .select({
        buyer: engagements.buyer,
        brandVoiceProfile: engagements.brandVoiceProfile,
        offerDetails: engagements.offerDetails,
        topCallQuestions: engagements.topCallQuestions,
        prospectMeets: engagements.prospectMeets,
        existingProof: engagements.existingProof,
        castingChoice: engagements.castingChoice,
        pinDownScriptPack: engagements.pinDownScriptPack,
        deletedAt: engagements.deletedAt,
      })
      .from(engagements)
      .where(
        and(
          eq(engagements.engagementId, id),
          eq(engagements.whopUserId, session.whopUserId),
          eq(engagements.workspaceId, activeWorkspace.workspaceId)
        )
      )
      .limit(1);

    if (!row) {
      return NextResponse.json({ error: "Engagement not found or access denied." }, { status: 404 });
    }
    if (row.deletedAt) {
      return NextResponse.json({ error: "Can't regenerate content for a deleted engagement." }, { status: 409 });
    }
    if (!row.pinDownScriptPack) {
      return NextResponse.json(
        { error: "No script pack exists yet for this client — it's generated by the setup wizard, not created here." },
        { status: 409 }
      );
    }

    const castingChoice = (row.castingChoice ?? undefined) as
      | "founder_on_camera"
      | "coach_on_camera"
      | "animation"
      | "other"
      | undefined;

    const scriptPack = await buildScriptPack({
      buyer: row.buyer,
      brandVoiceProfile: row.brandVoiceProfile,
      offerDetails: row.offerDetails ?? undefined,
      topCallQuestions: row.topCallQuestions ?? undefined,
      prospectMeets: row.prospectMeets ?? undefined,
      existingProof: row.existingProof ?? undefined,
      castingChoice,
    });

    await db
      .update(engagements)
      .set({
        pinDownScriptPack: {
          generatedAt: new Date().toISOString(),
          heroScript: scriptPack.heroScript,
          breakoutScripts: scriptPack.breakoutScripts,
          recordingChecklist: scriptPack.recordingChecklist,
        },
        updatedAt: new Date(),
      })
      .where(eq(engagements.engagementId, id));

    return NextResponse.json({ ok: true, scriptPack });
  } catch (err) {
    console.error("[engagements/[id]/regenerate/scripts POST]", err);
    return NextResponse.json({ error: "Failed to regenerate scripts." }, { status: 500 });
  }
}
