// src/lib/tours/tour-definitions.ts
//
// The actual tour content. One tour per product (Showtime, Reputation
// Manager, Cold Open, Whop Agent) plus "dashboard-basics" and
// "engagement-detail" for the pages that aren't product-scoped, and a
// "full-walkthrough" that's just all of them concatenated — so a first-
// time user can either pick exactly what they need or take the whole
// thing in one pass (both options live in the tour picker, see
// tour-launcher.tsx).
//
// Every product tour is generated by buildProductTour() rather than
// hand-written 4 times — the Library's per-skill mechanics (Configure/
// Analytics/status filters/the onboarding gate) are the literally same
// UI across all 4 products (see worker-card.tsx), so 4 near-duplicate
// step lists would just be 4 places to forget to update together.

import type { TourDefinition, TourStep } from "./types";

/** Substitutes `{engagementId}` into a step's route template. Returns
 * null (meaning "can't resolve this route yet") when the route needs an
 * engagement and there isn't a primary one for this workspace — the
 * provider treats that the same as any other step whose target never
 * appears: skip it. */
export function resolveTourRoute(route: string, engagementId: string | null): string | null {
  if (!route.includes("{engagementId}")) return route;
  if (!engagementId) return null;
  return route.replace("{engagementId}", engagementId);
}

const DASHBOARD_BASICS: TourStep[] = [
  {
    id: "create-button",
    route: "/dashboard",
    target: '[data-tour="top-nav-create"]',
    title: "Start anything from here",
    body: "New client, trigger a skill run, add a manual Queue task, or export a report — one button for every way to start something.",
    placement: "bottom-start",
  },
  {
    id: "overview-stats",
    route: "/dashboard",
    target: '[data-tour="dashboard-overview-stats"]',
    title: "Your week at a glance",
    body: "Completed runs, open issues, and the weekly trend — the numbers that actually change day to day, not a vanity total.",
    placement: "bottom",
  },
  {
    id: "activity",
    route: "/dashboard",
    target: '[data-tour="dashboard-activity"]',
    title: "Queue and Live Activity, in one place",
    body: "Every pending approval, blocker, alert, and skill run — past and present, across every client and product — lands in this one filterable list. Needs-action items float to the top; click any row to see the full detail on the right without losing your place in the list.",
    placement: "top",
  },
  {
    id: "sidebar-primary",
    route: "/dashboard",
    target: '[data-tour="sidebar-nav-primary"]',
    title: "Home, client profile, reports",
    body: "This workspace's one client's own page is always one click away here — no roster to dig through.",
    placement: "right",
  },
  {
    id: "sidebar-installed-skills",
    route: "/dashboard",
    target: '[data-tour="sidebar-installed-skills"]',
    title: "What's already running",
    body: "Every skill currently enabled for this client, with a quick on/off switch. To turn on something new, that's the Library — next tour.",
    placement: "right",
  },
  {
    id: "utility-rail",
    route: "/dashboard",
    target: '[data-tour="top-nav-utility-rail"]',
    title: "Calendar, Teammates, notifications",
    body: "The icons on the right cover everything that isn't a specific client or skill. Whether a client's actions wait for your approval is set on that client's page, under Modify → Automation mode.",
    placement: "bottom-end",
  },
];

const LIBRARY_BASICS: TourStep[] = [
  {
    id: "library-grid",
    route: "/dashboard/library",
    target: '[data-tour="library-grid"]',
    title: "Every worker you can install",
    body: "A worker (Showtime, Reputation Manager, Cold Open, Whop Agent) is the thing you install. The individual skills inside it get enabled once it's installed.",
    placement: "top",
  },
  {
    id: "library-install",
    route: "/dashboard/library",
    target: '[data-tour="product-card-install"]',
    title: "Install for this client",
    body: "Installing a worker doesn't turn anything on by itself — it just makes its skills available to enable, one at a time, on its own page.",
    placement: "top",
  },
  {
    id: "product-status-tabs",
    route: "/dashboard/library/showtime",
    target: '[data-tour="product-status-tabs"]',
    title: "Filter by status or category",
    body: "Once you're inside a worker's own page, these tabs narrow the skill list down to just what's enabled, not enabled, or in a specific category.",
    placement: "bottom",
  },
  {
    id: "product-skill-list",
    route: "/dashboard/library/showtime",
    target: '[data-tour="product-skill-list"]',
    title: "Enable, Configure, Analytics",
    body: "Every skill lives in this list. Click a row to open its own page, or use Configure/Analytics directly — same pattern on every worker's page.",
    placement: "top",
  },
];

const ENGAGEMENT_DETAIL: TourStep[] = [
  {
    id: "pause-control",
    route: "/dashboard/engagements/{engagementId}",
    target: '[data-tour="engagement-pause-control"]',
    title: "Pause this client",
    body: "Pausing stops every automated run for this client without disabling anything — flip it back on and every skill resumes exactly as configured.",
    placement: "bottom-end",
  },
  {
    id: "report",
    route: "/dashboard/engagements/{engagementId}",
    target: '[data-tour="engagement-report"]',
    title: "One report, every enabled skill",
    body: "This merges output from whichever skills are actually on for this client — Showtime and Reputation Manager together when both apply, not two separate cards.",
    placement: "top",
  },
  {
    id: "workers-panel",
    route: "/dashboard/engagements/{engagementId}",
    target: '[data-tour="engagement-workers-panel"]',
    title: "Every skill, live status",
    body: "The same on/off switches, Configure, and Analytics as the Library — but scoped to this one client, with its actual latest run right on the card.",
    placement: "top",
  },
];

interface ProductTourSpec {
  id: string;
  label: string;
  description: string;
  productPath: string;
  onboardingWorkerId: string;
  onboardingWorkerName: string;
}

const PRODUCT_TOUR_SPECS: ProductTourSpec[] = [
  {
    id: "showtime",
    label: "Showtime",
    description: "Booking-to-close automation — confirmation pages, pre-call sequences, call briefs, win-back.",
    productPath: "/dashboard/library/showtime",
    onboardingWorkerId: "pin-down",
    onboardingWorkerName: "Show Rate Setup",
  },
  {
    id: "reputation-manager",
    label: "Reputation Manager",
    description: "Review and mention monitoring across every platform this client is watched on.",
    productPath: "/dashboard/library/reputation-manager",
    onboardingWorkerId: "rep-onboarding",
    onboardingWorkerName: "Identity Setup",
  },
  {
    id: "cold-open",
    label: "Cold Open",
    description: "Outbound lead sourcing, sending, and reply sorting.",
    productPath: "/dashboard/library/cold-open",
    onboardingWorkerId: "icp-lock",
    onboardingWorkerName: "ICP Lock",
  },
  {
    id: "whop-agent",
    label: "Whop Agent",
    description: "Whop store operations — payouts, disputes, promos, ads.",
    productPath: "/dashboard/library/whop-agent",
    onboardingWorkerId: "whop-connect",
    onboardingWorkerName: "Connect Whop Account",
  },
];

/** Same 3-step shape for every product — the mechanics (status tabs, the
 * onboarding-gate concept, the skill list) are identical across all 4;
 * only the copy and which row to point at change. See this file's own
 * header for why this is generated instead of 4 hand-written tours. */
function buildProductTour(spec: ProductTourSpec): TourDefinition {
  return {
    id: spec.id,
    label: spec.label,
    description: spec.description,
    steps: [
      {
        id: "status-tabs",
        route: spec.productPath,
        target: '[data-tour="product-status-tabs"]',
        title: `${spec.label}'s skills`,
        body: `Filter this worker's own skill list by what's already enabled — everything here belongs to ${spec.label} specifically.`,
        placement: "bottom",
      },
      {
        id: "onboarding-worker",
        route: spec.productPath,
        target: `[data-tour="worker-row-${spec.onboardingWorkerId}"]`,
        title: spec.onboardingWorkerName,
        body: `This is where ${spec.label} starts. Every other skill in it stays locked until this one actually runs for this client — not just switched on, actually completed.`,
        placement: "top",
      },
      {
        id: "skill-list",
        route: spec.productPath,
        target: '[data-tour="product-skill-list"]',
        title: "Enable the rest",
        body: `Once ${spec.onboardingWorkerName} has run, every other ${spec.label} skill enables normally from this same list.`,
        placement: "top",
      },
    ],
  };
}

export const TOURS: TourDefinition[] = [
  { id: "dashboard-basics", label: "Dashboard Basics", description: "Orient yourself — Queue, Live Executions, sidebar, and the Create button.", steps: DASHBOARD_BASICS },
  { id: "library", label: "The Library", description: "Install a worker, then enable and configure the skills inside it.", steps: LIBRARY_BASICS },
  { id: "engagement-detail", label: "Your Client's Page", description: "Pause, reports, and every skill running for this one client.", steps: ENGAGEMENT_DETAIL },
  // One entry for every worker, not one per worker: the menu stays the
  // same size as workers are added (a new worker only adds a spec above).
  // A step whose worker page isn't there for this workspace is skipped by
  // the provider's target timeout.
  {
    id: "workers",
    label: "Your Workers",
    description: "How each worker starts: its setup skill runs first, then the rest enable from the same list.",
    steps: PRODUCT_TOUR_SPECS.flatMap((spec) => buildProductTour(spec).steps.map((s) => ({ ...s, id: `${spec.id}__${s.id}` }))),
  },
  // Each product's own three steps, kept as hidden tours: a setup form
  // starts its product's tour right after saving (startTour("showtime"),
  // "cold-open", "whop-agent"). Not listed in the picker, which only
  // shows "Your Workers".
  ...PRODUCT_TOUR_SPECS.map((spec) => ({ ...buildProductTour(spec), hidden: true })),
  {
    id: "full-walkthrough",
    label: "Full Walkthrough",
    description: "Everything above, back to back — the whole app in one pass.",
    steps: [
      { source: "dashboard-basics", steps: DASHBOARD_BASICS },
      { source: "library", steps: LIBRARY_BASICS },
      { source: "engagement-detail", steps: ENGAGEMENT_DETAIL },
      ...PRODUCT_TOUR_SPECS.map((spec) => ({ source: spec.id, steps: buildProductTour(spec).steps })),
    ].flatMap(({ source, steps }) => steps.map((s) => ({ ...s, id: `${source}__${s.id}` }))),
  },
];

export function getTour(tourId: string): TourDefinition | undefined {
  return TOURS.find((t) => t.id === tourId);
}
