import { NextResponse } from "next/server";
import { db } from "@/lib/db";
import { engagements } from "@/models/schema";
import { getSession } from "@/lib/session";
import { getActiveWorkspace } from "@/lib/workspace";
import { and, eq } from "drizzle-orm";
import { buildAdCreativeBriefs } from "@/features/pile-on/server/ad-creative-briefs";

/**
 * Manual "Regenerate now" for Pile-On's ad creative briefs — the
 * counterpart to the automatic single-pillar regenerate
 * conversation-intelligence.ts triggers off a live call (see
 * regenerateObjectionsBrief there). This one rebuilds all 4 briefs from
 * whatever's on the engagement row right now, for use right after editing
 * offer/voice/questions/objections/testimonials in the client details
 * drawer — those fields are baked into the briefs once at onboarding and
 * don't otherwise update on their own.
 *
 * Deliberately does NOT touch pinDownScriptPack or the confirmation page —
 * see /api/engagements/[id]/regenerate/scripts for scripts, and the
 * client-details-drawer.tsx copy explaining why the confirmation page
 * itself isn't offered a one-click regenerate here (its deploy step is
 * approval-gated).
 */
export async function POST(
  _req: Request,
  { params }: { params: Promise<{ id: string }> }
) {
  try {
    const { id } = await params;
    const session = await getSession();
    if (!session?.whopUserId) {
      return NextResponse.json({ error: "Unauthorized" }, { status: 401 });
    }
    const activeWorkspace = await getActiveWorkspace(session.whopUserId);

    const [row] = await db
      .select({
        buyer: engagements.buyer,
        brandVoiceProfile: engagements.brandVoiceProfile,
        offerDetails: engagements.offerDetails,
        topCallQuestions: engagements.topCallQuestions,
        topObjections: engagements.topObjections,
        existingProof: engagements.existingProof,
        adCreativeBriefs: engagements.adCreativeBriefs,
        deletedAt: engagements.deletedAt,
      })
      .from(engagements)
      .where(
        and(
          eq(engagements.engagementId, id),
          eq(engagements.whopUserId, session.whopUserId),
          eq(engagements.workspaceId, activeWorkspace.workspaceId)
        )
      )
      .limit(1);

    if (!row) {
      return NextResponse.json({ error: "Engagement not found or access denied." }, { status: 404 });
    }
    if (row.deletedAt) {
      return NextResponse.json({ error: "Can't regenerate content for a deleted engagement." }, { status: 409 });
    }
    if (!row.adCreativeBriefs) {
      return NextResponse.json(
        { error: "No ad creative briefs exist yet for this client — they're generated by the setup wizard, not created here." },
        { status: 409 }
      );
    }

    const { briefs } = await buildAdCreativeBriefs({
      buyer: row.buyer,
      brandVoiceProfile: row.brandVoiceProfile,
      offerDetails: row.offerDetails ?? undefined,
      topCallQuestions: row.topCallQuestions ?? undefined,
      topObjections: row.topObjections ?? undefined,
      existingProof: row.existingProof ?? undefined,
    });

    await db
      .update(engagements)
      .set({
        adCreativeBriefs: { generatedAt: new Date().toISOString(), briefs },
        updatedAt: new Date(),
      })
      .where(eq(engagements.engagementId, id));

    return NextResponse.json({ ok: true, briefs });
  } catch (err) {
    console.error("[engagements/[id]/regenerate/ad-creative-briefs POST]", err);
    return NextResponse.json({ error: "Failed to regenerate ad creative briefs." }, { status: 500 });
  }
}
